version: '3'

services:
  express:
    build: .
    ports:
      - "3000:3000"
      - "9100:9100"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
